keeptree: False
with-expecter: True
inpackage: True
dir: "{{.InterfaceDirRelative}}"
outpkg: "{{.PackageName}}"
filename: "{{.InterfaceName | snakecase}}_mock.go"

packages:
  flight-booking/internal/services/cache:
    interfaces:
      Cache:
