with-expecter: true
packages:
  flight-booking/internal/interfaces:
    config:
      dir: "internal/mocks"
      filename: "{{.InterfaceName}}.go"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "mocks"
    interfaces:
      RouteProvider:
      CacheService:
      RouteService:
      Logger:
      HTTPClient:
      MetricsCollector:
      ProviderManager:
      ConfigProvider: 