server:
  port: "8080"
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"
  graceful_shutdown_timeout: "30s"

log:
  level: "info"
  format: "json"

cache:
  enabled: true
  default_ttl: "5m"
  cleanup_interval: "10m"
  max_size: 10000

providers:
  provider1:
    enabled: true
    base_url: "https://api.provider1.com"
    timeout: "10s"
    retries: 3
  provider2:
    enabled: true
    base_url: "https://api.provider2.com"
    timeout: "10s"
    retries: 3 