version: '3'

env:
  GO_VERSION: 1.21
  BINARY_NAME: flight-booking

vars:
  GENERATED_DIR: ./internal/api/gen
  DOCS_DIR: ./docs

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  lint:
    desc: Run linter
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - golangci-lint run

  generate:
    desc: Generate all code (models, swagger, mocks)
    deps: [generate-openapi, generate-mocks]

  generate-openapi:
    desc: Generate models from OpenAPI spec
    sources:
      - "openapi.yaml"
    generates:
      - "{{.GENERATED_DIR}}/types_gen.go"
      - "{{.GENERATED_DIR}}/server_gen.go"
    cmds:
      - go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest
      - oapi-codegen -generate types -package gen openapi.yaml > {{.GENERATED_DIR}}/types_gen.go
      - oapi-codegen -generate gin -package gen openapi.yaml > {{.GENERATED_DIR}}/server_gen.go

  generate-mocks:
    desc: Generate mocks using mockery
    sources:
      - "internal/**/*.go"
    generates:
      - "internal/mocks/**/*.go"
    cmds:
      - go install github.com/vektra/mockery/v2@latest
      - mockery
